### ISSUE TITLE
这是自带的讯飞接口还是要自己申请呢

### ISSUE THREAD

**Issue by yaoing** [zyqzyq/ALSoundRecognition#1]
用ALDialog 发现有局限性

**Comment by checkyourface** [comment]
你好 请问一下 你现在可以使用这个语音识别的代码了吗

**Comment by checkyourface** [comment]
> 用ALDialog 发现有局限性

你好 请问你现在可以使用这个语音识别的代码了吗

**Comment by zyqzyq** [comment]
自带了讯飞的SDK，但是因为测试版，有500次每天的限制。
